version: '3.8'

services:
  pdf-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-extractor
    ports:
      - "3080:3080"
    volumes:
      - ./uploads:/usr/src/app/uploads
    env_file:
      - .env
    networks:
      - extractor-network

networks:
  extractor-network:
    driver: bridge 